name = "Toha"
license = "MIT"
licenselink = "https://github.com/hugo-toha/toha/blob/master/LICENSE"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
description = "A simple hugo theme for personal portfolio"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/hugo-toha/toha"

# If you have a running demo of the theme.
demosite = "https://hugo-toha.github.io/"
=======
min_version = "0.87.0"
name = "Toha"
>>>>>>> 46969da (updated to stable release)
=======
=======
>>>>>>> 2e395f05247e00814659ae78ebf9d7a5403b59c0
min_version = "0.87.0"
name = "Toha"
=======
description = "A simple hugo theme for personal portfolio"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/hugo-toha/toha"

# If you have a running demo of the theme.
demosite = "https://hugo-toha.github.io/"
>>>>>>> upstream/main
<<<<<<< HEAD
>>>>>>> 2e395f0 (initial for rebase)
=======
>>>>>>> 2e395f05247e00814659ae78ebf9d7a5403b59c0

tags = [
  "Portfolio",
  "Blog",
  "Resume",
  "Projects",
  "Gallery",
  "Multilingual",
  "Minimalist",
  "Responsive",
  "Customizable",
  "Google analytics",
  "Disqus",
  "Bootstrap",
  "Syntax highlighting",
]
features = [
  "Minimalist Design",
  "Fully Responsive",
  "Multiple Language Support",
  "Carefully Designed Cards",
  "Experience Timeline",
  "Achievement Gallery",
  "Sidebar to Categorize the Posts",
  "Short Codes",
  "Google Analytics Support",
  "Disqus Comment Support",
]

[author]
  homepage = "https://hossainemruz.github.io"
  name = "Emruz Hossain"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.118.0"